In [152]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pylab as plt


In [153]:
df = pd.read_csv('CSRIC_Best_Practices.csv')

In [154]:
df.shape

(1092, 20)

In [155]:
df.head()

BP Number          Priority  \
0  12-10-0436  Highly Important   
1  12-10-0437  Highly Important   
2  12-10-0440  Highly Important   
3  12-10-0447         Important   
4  12-10-0448  Highly Important   

                                         Description  \
0  Network Operators, Service Providers, and Publ...   
1  Network Operators and Service Providers should...   
2  Network Operators and Service Providers should...   
3  Network Operators and Service Providers should...   
4  Equipment Suppliers should  where feasible, pr...   

                                     Network Type(s)  \
0  Cable; Internet/Data; Satellite; Wireless; Wir...   
1                                     Internet/Data;   
2                                     Internet/Data;   
3  Cable; Internet/Data; Satellite; Wireless; Wir...   
4  Cable; Internet/Data; Satellite; Wireless; Wir...   

                                    Industry Role(s)  \
0  Service Provider; Network Operator; Public Saf...   
1                Service Provider; Network Operator;   
2                Service Provider; Network Operator;   
3                Service Provider; Network Operator;   
4                                Equipment Supplier;   

                                            Keywords  \
0                    Network Operations; Procedures;   
1  Cyber Security; Network Operations; Network Pr...   
2          Industry Cooperation; Network Operations;   
3                       Liaison; Network Operations;   
4  Hardware; Network Elements; Network Provisioni...   

   Public Safety and Disaster  \
0                        True   
1                       False   
2                       False   
3                       False   
4                       False   

                                           Reference  cable  internet/Data  \
0                                                NaN   True           True   
1                                                NaN  False           True   
2                                                NaN  False           True   
3  Note: This Best practice could impact 9-1-1 op...   True           True   
4                                                NaN   True           True   

   satellite  wireless  wireline  Service Provider  Network Operator  \
0       True      True      True              True              True   
1      False     False     False              True              True   
2      False     False     False              True              True   
3       True      True      True              True              True   
4       True      True      True             False             False   

   Priority (1,2,3)  Equipment Supplier  Property Manager  Government  \
0               2.0               False             False       False   
1               2.0               False             False       False   
2               2.0               False             False       False   
3               1.0               False             False       False   
4               2.0                True             False       False   

   Public Safety  
0           True  
1          False  
2          False  
3          False  
4          False

In [156]:
df.isna().any()

BP Number                     False
Priority                       True
Description                   False
Network Type(s)               False
Industry Role(s)              False
Keywords                       True
Public Safety and Disaster    False
Reference                      True
cable                         False
internet/Data                 False
satellite                     False
wireless                      False
wireline                      False
Service Provider              False
Network Operator              False
Priority (1,2,3)               True
Equipment Supplier            False
Property Manager              False
Government                    False
Public Safety                 False
dtype: bool

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1092 entries, 0 to 1091
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   BP Number                   1092 non-null   object 
 1   Priority                    1006 non-null   object 
 2   Description                 1092 non-null   object 
 3   Network Type(s)             1092 non-null   object 
 4   Industry Role(s)            1092 non-null   object 
 5   Keywords                    1088 non-null   object 
 6   Public Safety and Disaster  1092 non-null   bool   
 7   Reference                   490 non-null    object 
 8   cable                       1092 non-null   bool   
 9   internet/Data               1092 non-null   bool   
 10  satellite                   1092 non-null   bool   
 11  wireless                    1092 non-null   bool   
 12  wireline                    1092 non-null   bool   
 13  Service Provider            1092 

In [158]:
df['Priority'].value_counts()

Important           465
Highly Important    350
Critical            191
Name: Priority, dtype: int64

In [159]:
df['Priority (1,2,3)'].value_counts()

1.0    465
2.0    350
3.0    191
Name: Priority (1,2,3), dtype: int64

In [201]:
missing = pd.DataFrame(df.isnull().mean()*100, columns=['missing_%'])
missing.sort_values(by='missing_%', ascending=False)

missing_%
Public Safety and Disaster        0.0
cable                             0.0
internet/Data                     0.0
satellite                         0.0
wireless                          0.0
wireline                          0.0
Service Provider                  0.0
Network Operator                  0.0
Priority (1,2,3)                  0.0
Equipment Supplier                0.0
Property Manager                  0.0
Government                        0.0
Public Safety                     0.0

In [161]:
df['Network Type(s)'].value_counts()

Cable; Internet/Data; Satellite; Wireless; Wireline;    715
Internet/Data;                                          126
Wireless;                                                79
Cable; Internet/Data; Wireline;                          64
Cable; Internet/Data; Wireless; Wireline;                58
Cable; Internet/Data; Satellite; Wireless;                9
Satellite;                                                8
Cable; Wireless; Wireline;                                7
Wireline;                                                 6
Cable; Internet/Data; Satellite; Wireline;                5
Cable; Internet/Data; Wireless;                           3
Cable; Satellite; Wireless; Wireline;                     2
Internet/Data; Wireless;                                  2
Wireless; Wireline;                                       1
Satellite; Wireless;                                      1
Cable;                                                    1
Cable; Wireless;                        

In [162]:
df['Industry Role(s)'].value_counts()

Service Provider; Network Operator;                                                                     204
Service Provider; Network Operator; Public Safety;                                                      181
Service Provider; Network Operator; Equipment Supplier; Public Safety;                                  175
Network Operator;                                                                                        79
Service Provider; Network Operator; Public Safety; Property Manager;                                     64
Service Provider; Network Operator; Equipment Supplier; Public Safety; Property Manager;                 62
Equipment Supplier;                                                                                      61
Service Provider; Network Operator; Equipment Supplier;                                                  61
Service Provider;                                                                                        59
Network Operator; Public Saf

In [163]:
df['Keywords'].value_counts().head(20)

Cyber Security; Intrusion Detection; Network Operations;                                          31
Cyber Security; Intrusion Detection;                                                              21
Cyber Security; Network Operations;                                                               18
Cyber Security; Network Elements; Network Operations;                                             17
Cyber Security; Encryption; Information Protection; Intrusion Detection;                          15
Cyber Security;                                                                                   14
Cyber Security; Disaster Recovery; Emergency Preparedness; Intrusion Detection;                   11
Network Operations;                                                                               11
Cyber Security; Encryption; Information Protection; Public Safety; Public Safety and Disaster;    10
Cyber Security; Encryption; Intrusion Detection;                                           

In [164]:
df['BP Number'].nunique()

1092

In [165]:
df.drop(['Keywords','Reference', 'BP Number', 'Priority', 'Description'], axis=1, inplace=True)

In [166]:
df.drop(['Industry Role(s)', 'Network Type(s)'], axis=1, inplace=True)

In [202]:
df

Public Safety and Disaster  cable  internet/Data  satellite  wireless  \
0                           True   True           True       True      True   
1                          False  False           True      False     False   
2                          False  False           True      False     False   
3                          False   True           True       True      True   
4                          False   True           True       True      True   
...                          ...    ...            ...        ...       ...   
1087                       False  False          False      False     False   
1088                       False  False          False      False     False   
1089                        True   True           True      False     False   
1090                       False   True           True       True      True   
1091                        True   True           True       True      True   

      wireline  Service Provider  Network Operator  Priority (1,2,3)  \
0         True              True              True                 2   
1        False              True              True                 2   
2        False              True              True                 2   
3         True              True              True                 1   
4         True             False             False                 2   
...        ...               ...               ...               ...   
1087      True              True              True                 1   
1088      True             False              True                 1   
1089      True              True              True                 1   
1090      True              True              True                 1   
1091      True             False             False                 1   

      Equipment Supplier  Property Manager  Government  Public Safety  
0                  False             False       False           True  
1                  False             False       False          False  
2                  False             False       False          False  
3                  False             False       False          False  
4                   True             False       False          False  
...                  ...               ...         ...            ...  
1087                True             False       False          False  
1088               False             False       False          False  
1089               False             False       False           True  
1090               False             False       False          False  
1091               False             False       False           True  

[1092 rows x 13 columns]

In [172]:
df['Priority (1,2,3)'] = df['Priority (1,2,3)'].fillna(1.0)

In [173]:
df['Priority (1,2,3)'] = df['Priority (1,2,3)'].astype(int)

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1092 entries, 0 to 1091
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Public Safety and Disaster  1092 non-null   bool 
 1   cable                       1092 non-null   bool 
 2   internet/Data               1092 non-null   bool 
 3   satellite                   1092 non-null   bool 
 4   wireless                    1092 non-null   bool 
 5   wireline                    1092 non-null   bool 
 6   Service Provider            1092 non-null   bool 
 7   Network Operator            1092 non-null   bool 
 8   Priority (1,2,3)            1092 non-null   int64
 9   Equipment Supplier          1092 non-null   bool 
 10  Property Manager            1092 non-null   bool 
 11  Government                  1092 non-null   bool 
 12  Public Safety               1092 non-null   bool 
dtypes: bool(12), int64(1)
memory usage: 21.5 KB


In [176]:
X = df.drop('Priority (1,2,3)', axis=1)
y = df['Priority (1,2,3)']

In [177]:
X.head()

Public Safety and Disaster  cable  internet/Data  satellite  wireless  \
0                        True   True           True       True      True   
1                       False  False           True      False     False   
2                       False  False           True      False     False   
3                       False   True           True       True      True   
4                       False   True           True       True      True   

   wireline  Service Provider  Network Operator  Equipment Supplier  \
0      True              True              True               False   
1     False              True              True               False   
2     False              True              True               False   
3      True              True              True               False   
4      True             False             False                True   

   Property Manager  Government  Public Safety  
0             False       False           True  
1             False       False          False  
2             False       False          False  
3             False       False          False  
4             False       False          False

In [178]:
y.head()

0    2
1    2
2    2
3    1
4    2
Name: Priority (1,2,3), dtype: int64

In [179]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)

In [198]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [326]:
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, precision_score

dummy_classifier = DummyClassifier(strategy='stratified')

dummy_classifier.fit(X_train, y_train)

dummy_pred = dummy_classifier.predict(X_train)

In [325]:
result = confusion_matrix(y_train, dummy_pred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_train, dummy_pred)
print('Classification Report:')
print (result1)
result2 = accuracy_score(y_train, dummy_pred)
print('Accuracy:',result2)

Confusion Matrix:
[[212 116  57]
 [116  72  57]
 [ 58  55  21]]
Classification Report:
              precision    recall  f1-score   support

           1       0.55      0.55      0.55       385
           2       0.30      0.29      0.30       245
           3       0.16      0.16      0.16       134

    accuracy                           0.40       764
   macro avg       0.33      0.33      0.33       764
weighted avg       0.40      0.40      0.40       764

Accuracy: 0.3992146596858639


In [206]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RepeatedStratifiedKFold


In [301]:
from sklearn.model_selection import GridSearchCV
knn_classifier = KNeighborsClassifier()
params_knn = {'n_neighbors':[5,6,7,8,9,10], 'leaf_size':[1,2,3,5],
              'weights':['uniform', 'distance'],
              'algorithm':['auto', 'ball_tree','kd_tree','brute']}

gs_knn = GridSearchCV(estimator=knn_classifier, param_grid=params_knn, cv=cv_method)

gs_knn.fit(X_train, y_train)
print("Best Hyper Parameters:\n",gs_knn.best_params_)

Best Hyper Parameters:
 {'algorithm': 'auto', 'leaf_size': 1, 'n_neighbors': 6, 'weights': 'uniform'}


In [300]:
gs_knn_pred = gs_knn.predict(X_train)

result = confusion_matrix(y_train, gs_knn_pred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_train, gs_knn_pred)
print('Classification Report:')
print (result1)
result2 = accuracy_score(y_train, gs_knn_pred)
print('Accuracy:',result2)

Confusion Matrix:
[[322  59   4]
 [161  78   6]
 [ 87  30  17]]
Classification Report:
              precision    recall  f1-score   support

           1       0.56      0.84      0.67       385
           2       0.47      0.32      0.38       245
           3       0.63      0.13      0.21       134

    accuracy                           0.55       764
   macro avg       0.55      0.43      0.42       764
weighted avg       0.54      0.55      0.50       764

Accuracy: 0.5458115183246073


In [261]:
rf_classifier = RandomForestClassifier()
params_rf = {'criterion':['gini','entropy'], 'n_estimators':[10,15,20,25,30],
             'min_samples_leaf':[1,2,3], 'min_samples_split':[3,4,5,6,7],
             'random_state':[123]}

gs_rf = GridSearchCV(estimator=rf_classifier, param_grid=params_rf, cv=cv_method)

gs_rf.fit(X_train, y_train)

print("Best Hyper Parameters:\n",gs_rf.best_params_)

Best Hyper Parameters:
 {'criterion': 'gini', 'min_samples_leaf': 3, 'min_samples_split': 7, 'n_estimators': 25, 'random_state': 123}


In [262]:
gs_rf_pred = gs_rf.predict(X_train)

In [263]:
result = confusion_matrix(y_train, gs_rf_pred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_train, gs_rf_pred)
print('Classification Report:')
print (result1)
result2 = accuracy_score(y_train, gs_rf_pred)
print('Accuracy:',result2)

Confusion Matrix:
[[324  58   3]
 [161  80   4]
 [ 90  29  15]]
Classification Report:
              precision    recall  f1-score   support

           1       0.56      0.84      0.67       385
           2       0.48      0.33      0.39       245
           3       0.68      0.11      0.19       134

    accuracy                           0.55       764
   macro avg       0.57      0.43      0.42       764
weighted avg       0.56      0.55      0.50       764

Accuracy: 0.5484293193717278
